#开发配置
spring:
  datasource:
    url: jdbc:mysql://192.168.15.3:3306/wode
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp